#:include screens/association.kv
#:include screens/profil.kv
#:include screens/materiels.kv

<RootWidget>:
    orientation: 'vertical'
    padding: dp(10)
    spacing: dp(10)
    canvas.before:
        Color:
            rgba: 0.68, 0.85, 0.90, 1  # bleu ciel
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [15]

    BoxLayout:
        size_hint_y: None
        height: dp(40)
        spacing: dp(8)
        padding: dp(5), 0

        Button:
            text: "* Matériels"
            background_normal: ''
            background_color: 1, 1, 1, 1
            color: 0, 0, 0, 1
            font_size: dp(14)
            on_release: screen_manager.current = "materiels"

        Button:
            text: "> Panier"
            background_normal: ''
            background_color: 1, 1, 1, 1
            color: 0, 0, 0, 1
            font_size: dp(14)
            on_release: screen_manager.current = "panier"

        Button:
            text: "<3 Favoris"
            background_normal: ''
            background_color: 1, 1, 1, 1
            color: 0, 0, 0, 1
            font_size: dp(14)
            on_release: screen_manager.current = "wishlist"



    ScreenManager:
        id: screen_manager

        MaterielsScreen:
        PanierScreen:
        WishlistScreen:
        AssociationScreen:
        ProfilScreen:

    BoxLayout:
        size_hint_y: None
        height: dp(50)
        spacing: dp(10)

        Button:
            text: "🏢 Association"
            background_normal: ''
            background_color: 0.8, 0.88, 1, 1
            color: 0, 0, 0, 1
            font_size: dp(16)
            on_release: screen_manager.current = "association"

        Button:
            text: "👤 Profil"
            background_normal: ''
            background_color: 0.8, 0.88, 1, 1
            color: 0, 0, 0, 1
            font_size: dp(16)
            on_release: screen_manager.current = "profil"
