FROM python:3.11-slim

WORKDIR /app
RUN apt-get update && apt-get install -y gcc
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
