"""add tables

Revision ID: 5cea29b3237b
Revises: 
Create Date: 2025-11-25 14:30:48.866175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cea29b3237b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_text', sa.String(length=15), nullable=True),
    sa.Column('target', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profil_name'), 'profil', ['name'], unique=False)
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('ville', sa.String(length=30), nullable=True),
    sa.Column('addresse', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.Column('mail', sa.String(length=30), nullable=True),
    sa.Column('logo', sa.String(length=30), nullable=True),
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_association_name'), 'association', ['name'], unique=False)
    op.create_table('shop_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_cart_creation_date'), 'shop_cart', ['creation_date'], unique=False)
    op.create_index(op.f('ix_shop_cart_last_update_date'), 'shop_cart', ['last_update_date'], unique=False)
    op.create_index(op.f('ix_shop_cart_profil_id'), 'shop_cart', ['profil_id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=15), nullable=True),
    sa.Column('qty_available', sa.Integer(), nullable=True),
    sa.Column('resources_unit_cost', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(length=15), nullable=True),
    sa.Column('warning_nb', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['association.id'], ),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_association_id'), 'resource', ['association_id'], unique=False)
    op.create_index(op.f('ix_resource_profil_id'), 'resource', ['profil_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.Column('retire', sa.Boolean(), nullable=True),
    sa.Column('rendu', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=15), nullable=True),
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_end_date'), 'loan', ['end_date'], unique=False)
    op.create_index(op.f('ix_loan_free'), 'loan', ['free'], unique=False)
    op.create_index(op.f('ix_loan_profil_id'), 'loan', ['profil_id'], unique=False)
    op.create_index(op.f('ix_loan_rendu'), 'loan', ['rendu'], unique=False)
    op.create_index(op.f('ix_loan_resource_id'), 'loan', ['resource_id'], unique=False)
    op.create_index(op.f('ix_loan_retire'), 'loan', ['retire'], unique=False)
    op.create_index(op.f('ix_loan_start_date'), 'loan', ['start_date'], unique=False)
    op.create_table('shop_cart_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('shop_cart_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['shop_cart_id'], ['shop_cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_cart_detail_profil_id'), 'shop_cart_detail', ['profil_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_detail_resource_id'), 'shop_cart_detail', ['resource_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_detail_shop_cart_id'), 'shop_cart_detail', ['shop_cart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_cart_detail_shop_cart_id'), table_name='shop_cart_detail')
    op.drop_index(op.f('ix_shop_cart_detail_resource_id'), table_name='shop_cart_detail')
    op.drop_index(op.f('ix_shop_cart_detail_profil_id'), table_name='shop_cart_detail')
    op.drop_table('shop_cart_detail')
    op.drop_index(op.f('ix_loan_start_date'), table_name='loan')
    op.drop_index(op.f('ix_loan_retire'), table_name='loan')
    op.drop_index(op.f('ix_loan_resource_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_rendu'), table_name='loan')
    op.drop_index(op.f('ix_loan_profil_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_free'), table_name='loan')
    op.drop_index(op.f('ix_loan_end_date'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_resource_profil_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_association_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_shop_cart_profil_id'), table_name='shop_cart')
    op.drop_index(op.f('ix_shop_cart_last_update_date'), table_name='shop_cart')
    op.drop_index(op.f('ix_shop_cart_creation_date'), table_name='shop_cart')
    op.drop_table('shop_cart')
    op.drop_index(op.f('ix_association_name'), table_name='association')
    op.drop_table('association')
    op.drop_index(op.f('ix_profil_name'), table_name='profil')
    op.drop_table('profil')
    op.drop_table('i18n')
    # ### end Alembic commands ###
