"""db init

Revision ID: cbc3d4da5958
Revises: ff3736147b14
Create Date: 2025-05-19 14:25:28.266415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc3d4da5958'
down_revision = 'ff3736147b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_association_name'), 'association', ['name'], unique=False)
    op.create_index(op.f('ix_association_profil_id'), 'association', ['profil_id'], unique=False)
    op.create_index(op.f('ix_loan_end_date'), 'loan', ['end_date'], unique=False)
    op.create_index(op.f('ix_loan_free'), 'loan', ['free'], unique=False)
    op.create_index(op.f('ix_loan_rendu'), 'loan', ['rendu'], unique=False)
    op.create_index(op.f('ix_loan_resource_id'), 'loan', ['resource_id'], unique=False)
    op.create_index(op.f('ix_loan_retire'), 'loan', ['retire'], unique=False)
    op.create_index(op.f('ix_loan_start_date'), 'loan', ['start_date'], unique=False)
    op.create_index(op.f('ix_profil_name'), 'profil', ['name'], unique=False)
    op.create_index(op.f('ix_profil_management_creation_right'), 'profil_management', ['creation_right'], unique=False)
    op.create_index(op.f('ix_profil_management_delete_right'), 'profil_management', ['delete_right'], unique=False)
    op.create_index(op.f('ix_profil_management_managed_profil_id'), 'profil_management', ['managed_profil_id'], unique=False)
    op.create_index(op.f('ix_profil_management_master_profil_id'), 'profil_management', ['master_profil_id'], unique=False)
    op.create_index(op.f('ix_profil_management_read_right'), 'profil_management', ['read_right'], unique=False)
    op.create_index(op.f('ix_profil_management_update_right'), 'profil_management', ['update_right'], unique=False)
    op.create_index(op.f('ix_profil_resource_management_creation_right'), 'profil_resource_management', ['creation_right'], unique=False)
    op.create_index(op.f('ix_profil_resource_management_delete_right'), 'profil_resource_management', ['delete_right'], unique=False)
    op.create_index(op.f('ix_profil_resource_management_profil_id'), 'profil_resource_management', ['profil_id'], unique=False)
    op.create_index(op.f('ix_profil_resource_management_read_right'), 'profil_resource_management', ['read_right'], unique=False)
    op.create_index(op.f('ix_profil_resource_management_update_right'), 'profil_resource_management', ['update_right'], unique=False)
    op.create_index(op.f('ix_resource_resource_category_id'), 'resource', ['resource_category_id'], unique=False)
    op.create_index(op.f('ix_resource_resource_cost_id'), 'resource', ['resource_cost_id'], unique=False)
    op.create_index(op.f('ix_resource_resource_type_id'), 'resource', ['resource_type_id'], unique=False)
    op.create_index(op.f('ix_resource_category_name'), 'resource_category', ['name'], unique=False)
    op.create_index(op.f('ix_resource_cost_name'), 'resource_cost', ['name'], unique=False)
    op.create_index(op.f('ix_resource_cost_time_cost'), 'resource_cost', ['time_cost'], unique=False)
    op.create_index(op.f('ix_resource_type_name'), 'resource_type', ['name'], unique=False)
    op.create_index(op.f('ix_shop_cart_creation_date'), 'shop_cart', ['creation_date'], unique=False)
    op.create_index(op.f('ix_shop_cart_last_update_date'), 'shop_cart', ['last_update_date'], unique=False)
    op.create_index(op.f('ix_shop_cart_user_id'), 'shop_cart', ['user_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_detail_resource_id'), 'shop_cart_detail', ['resource_id'], unique=False)
    op.create_index(op.f('ix_shop_cart_detail_shop_cart_id'), 'shop_cart_detail', ['shop_cart_id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_profil_id'), 'user', ['profil_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profil_id'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_shop_cart_detail_shop_cart_id'), table_name='shop_cart_detail')
    op.drop_index(op.f('ix_shop_cart_detail_resource_id'), table_name='shop_cart_detail')
    op.drop_index(op.f('ix_shop_cart_user_id'), table_name='shop_cart')
    op.drop_index(op.f('ix_shop_cart_last_update_date'), table_name='shop_cart')
    op.drop_index(op.f('ix_shop_cart_creation_date'), table_name='shop_cart')
    op.drop_index(op.f('ix_resource_type_name'), table_name='resource_type')
    op.drop_index(op.f('ix_resource_cost_time_cost'), table_name='resource_cost')
    op.drop_index(op.f('ix_resource_cost_name'), table_name='resource_cost')
    op.drop_index(op.f('ix_resource_category_name'), table_name='resource_category')
    op.drop_index(op.f('ix_resource_resource_type_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_resource_cost_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_resource_category_id'), table_name='resource')
    op.drop_index(op.f('ix_profil_resource_management_update_right'), table_name='profil_resource_management')
    op.drop_index(op.f('ix_profil_resource_management_read_right'), table_name='profil_resource_management')
    op.drop_index(op.f('ix_profil_resource_management_profil_id'), table_name='profil_resource_management')
    op.drop_index(op.f('ix_profil_resource_management_delete_right'), table_name='profil_resource_management')
    op.drop_index(op.f('ix_profil_resource_management_creation_right'), table_name='profil_resource_management')
    op.drop_index(op.f('ix_profil_management_update_right'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_management_read_right'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_management_master_profil_id'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_management_managed_profil_id'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_management_delete_right'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_management_creation_right'), table_name='profil_management')
    op.drop_index(op.f('ix_profil_name'), table_name='profil')
    op.drop_index(op.f('ix_loan_start_date'), table_name='loan')
    op.drop_index(op.f('ix_loan_retire'), table_name='loan')
    op.drop_index(op.f('ix_loan_resource_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_rendu'), table_name='loan')
    op.drop_index(op.f('ix_loan_free'), table_name='loan')
    op.drop_index(op.f('ix_loan_end_date'), table_name='loan')
    op.drop_index(op.f('ix_association_profil_id'), table_name='association')
    op.drop_index(op.f('ix_association_name'), table_name='association')
    # ### end Alembic commands ###
